/// Flutter icons Allerhand
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Allerhand
///      fonts:
///       - asset: fonts/Allerhand.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Allerhand {
  Allerhand._();

  static const _kFontFam = 'Allerhand';
  static const String? _kFontPkg = null;

  static const IconData questionBubble =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
