/// Flutter icons AllerhandIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AllerhandIcons
///      fonts:
///       - asset: fonts/AllerhandIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AllerhandIcons {
  AllerhandIcons._();

  static const _kFontFam = 'AllerhandIcons';
  static const String? _kFontPkg = null;

  static const IconData audioguide = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_bubble = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cafe = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData case_icon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compas = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData friends_circle = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_place = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circle = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radioguide = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stairs = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wardrobe = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wc_m = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wc_w = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
